#!/bin/sh

DESTDIR=/cygdrive/d/
OPTS="conv=fsync"
SYNC=0

if [ -d /Volumes/DAPLINK ]; then
  DESTDIR=/Volumes/DAPLINK
  OPTS=""
  SYNC=1
elif [ -d /mnt/sdcard -a -f /mnt/sdcard/MBED.HTM ]; then
  DESTDIR=/mnt/sdcard
  OPTS="oflag=dsync bs=512 status=progress"
  SYNC=1
fi

dd if=build/ArchMax.bin of=$DESTDIR/ArchMax.bin $OPTS

if [ "$SYNC" == 1 ]; then
  sync
else
  sleep 2
fi

echo hit reset button when red light is done
