#!/bin/sh

DESTDIR=/cygdrive/d/
OPTS="conv=fsync"

if [ -d /Volumes/DAPLINK ]; then
  DESTDIR=/Volumes/DAPLINK
  OPTS=""
fi

dd if=build/ArchMax.bin of=$DESTDIR/ArchMax.bin $OPTS

if [ -z "$OPTS" ]; then
  sync
else
  sleep 2
fi

echo hit reset button when red light is done
