#!/usr/bin/perl

use strict;

while(<>) {
  if(/^offset: ([0-9-]+) P=([0-9-]+) I=([0-9-]+) D=([0-9-]+) ppb=([0-9-]+) T=([0-9-]+) delay ([0-9]+)$/) {
    my($offset,$p,$i,$d,$total,$time,$delay) = ($1,$2,$3,$4,$5,$6,$7);
    $time -= 2208988800;
    print "$time $offset $p $i $d $total $delay\n";
  } elsif(/^ptp: ([0-9-]+) P=([0-9-]+) I=([0-9-]+) D=([0-9-]+) ppb=([0-9-]+) T=([0-9-]+)$/) {
    my($offset,$p,$i,$d,$total,$time) = ($1,$2,$3,$4,$5,$6);
    $time -= 2208988800;
    $offset = $offset / 4.294967296;
    print "$time $offset $p $i $d $total\n";
  } else {
    print STDERR "unknown line $_";
  }
}
