#!/bin/sh

RUN=5-19-2020
STARTTIME=1589949339

for i in offset ptp; do
  echo $i
  if [ \! -f $i-${RUN}.log -o ${RUN}.log -nt $i-${RUN}.log ]; then
    grep -a ^$i: ${RUN}.log | ./parse-offset | awk '($1 > '$STARTTIME' && ($1 < 1591904849 || $1 > 1591904853)) { print }' >$i-${RUN}.log
  fi
  if [ \! -f $i-${RUN}.history -o $i-${RUN}.log -nt $i-${RUN}.history ]; then
    ./histogram 1 1 <$i-${RUN}.log >$i-${RUN}.history
  fi
done

for i in 10.1.2.128 10.1.2.198; do
  echo $i
  if [ \! -f $i-${RUN}.log -o ${RUN}.log -nt $i-${RUN}.log ]; then
    grep -a "^$i " ${RUN}.log | ./parse-ntp | awk '($1 > '$STARTTIME') { print }' >$i-${RUN}.log
  fi
  if [ \! -f $i-${RUN}.history -o $i-${RUN}.log -nt $i-${RUN}.history ]; then
    ./histogram 4 1 <$i-${RUN}.log >$i-${RUN}.history
  fi
done

echo graphs
gnuplot <<EOF
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "offset-${RUN}.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.0f ns" nomirror
set title "offset between tim2/pps (after sync)"
set key top right box
plot \\
    'offset-${RUN}.log' using 1:2 title 'pps' with line
EOF

gnuplot <<EOF
set terminal png size 900,600
set output "pi-${RUN}.png"
set xdata time
set timefmt "%s"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f ppm" nomirror
set title "P/I outputs for TIM2"
set key top right box
plot \\
    'offset-${RUN}.log' using 1:(\$3/1000) title 'p' with line, \\
    'offset-${RUN}.log' using 1:(\$4/1000) title 'i' with line
EOF

gnuplot <<EOF
set terminal png size 900,600
set output "d-${RUN}.png"
set xdata time
set timefmt "%s"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f ppm" nomirror
set title "D outputs for TIM2"
set key top right box
plot \\
    'offset-${RUN}.log' using 1:(\$5/1000) title 'd' with line
EOF

gnuplot <<EOF
set terminal png size 900,600
set output "total-${RUN}.png"
set xdata time
set timefmt "%s"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f ppm" nomirror
set title "total outputs for TIM2"
set key top right box
plot \\
    'offset-${RUN}.log' using 1:(\$6/1000) title 'total' with line
EOF

gnuplot <<EOF
set terminal png size 900,600
set output "gps-${RUN}.png"
set xdata time
set timefmt "%s"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.0f ms" nomirror
set title "PPS to GPS message delay"
set key top right box
plot \\
    'offset-${RUN}.log' using 1:7 title 'gps' with line
EOF

NINETYNINE=`./percentile 1 99 offset-${RUN}.log`
SEVENTYFIVE=`./percentile 1 75 offset-${RUN}.log`
TWENTYFIVE=`./percentile 1 25 offset-${RUN}.log`
ONE=`./percentile 1 1 offset-${RUN}.log`

gnuplot <<EOF
set terminal png size 900,600
set output "histogram-${RUN}.png"
set grid
set xtic rotate by -45 scale 0
set title "TIM2 Clock Offsets - Histogram"
set xtics format "%1.0f ns" nomirror
set label 1 gprintf("99%% = %1.0f ns",$NINETYNINE) at $NINETYNINE, graph 0.91 left front offset 1,-1
set style arrow 1 nohead
set arrow from $NINETYNINE,0 to $NINETYNINE,graph 0.91 as 1
set label 2 gprintf(" 1%% = %1.0f ns",$ONE) at $ONE, graph 0.91 right front offset -1,-1
set style arrow 2 nohead
set arrow from $ONE,0 to $ONE,graph 0.91 as 2
set label 3 gprintf("25%% = %1.0f ns",$TWENTYFIVE) at $TWENTYFIVE, graph 0.7 right front offset -1,-1
set style arrow 3 nohead
set arrow from $TWENTYFIVE,0 to $TWENTYFIVE,graph 0.7 as 3
set label 4 gprintf("75%% = %1.0f ns",$SEVENTYFIVE) at $SEVENTYFIVE, graph 0.7 left front offset 1,-1
set style arrow 4 nohead
set arrow from $SEVENTYFIVE,0 to $SEVENTYFIVE,graph 0.7 as 4
set key off
set xrange [-5000:5000]
plot \\
 "offset-${RUN}.history" using 1:2 title "histogram" with boxes
EOF

gnuplot <<EOF
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "ptp-${RUN}.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.0f ns" nomirror
set title "offset between tim2/ptp (after sync)"
set key top right box
plot \\
    'ptp-${RUN}.log' using 1:2 title 'ptp' with line
EOF

gnuplot <<EOF
set terminal png size 900,600
set output "ptp-pi-${RUN}.png"
set xdata time
set timefmt "%s"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f ppm" nomirror
set title "P/I outputs for PTP"
set key top right box
plot \\
    'ptp-${RUN}.log' using 1:(\$3/1000) title 'p' with line, \\
    'ptp-${RUN}.log' using 1:(\$4/1000) title 'i' with line
EOF

gnuplot <<EOF
set terminal png size 900,600
set output "ptp-d-${RUN}.png"
set xdata time
set timefmt "%s"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f ppm" nomirror
set title "D outputs for PTP"
set key top right box
plot \\
    'ptp-${RUN}.log' using 1:(\$5/1000) title 'd' with line
EOF

gnuplot <<EOF
set terminal png size 900,600
set output "ptp-total-${RUN}.png"
set xdata time
set timefmt "%s"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f ppm" nomirror
set title "total outputs for PTP"
set key top right box
plot \\
    'ptp-${RUN}.log' using 1:(\$6/1000) title 'total' with line
EOF

gnuplot <<EOF
set terminal png size 900,600
set output "ptp-diff-${RUN}.png"
set xdata time
set timefmt "%s"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f ppm" nomirror
set title "freq difference for PTP"
set key top right box
plot \\
    'ptp-${RUN}.log' using 1:((\$5-\$6)/1000) title 'difference' with line
EOF

NINETYNINE=`./percentile 1 99 ptp-${RUN}.log`
SEVENTYFIVE=`./percentile 1 75 ptp-${RUN}.log`
TWENTYFIVE=`./percentile 1 25 ptp-${RUN}.log`
ONE=`./percentile 1 1 ptp-${RUN}.log`

gnuplot <<EOF
set terminal png size 900,600
set output "ptp-histogram-${RUN}.png"
set grid
set xtic rotate by -45 scale 0
set title "PTP Clock Offsets - Histogram"
set xtics format "%1.0f ns" nomirror
set label 1 gprintf("99%% = %1.0f ns",$NINETYNINE) at $NINETYNINE, graph 0.91 left front offset 1,-1
set style arrow 1 nohead
set arrow from $NINETYNINE,0 to $NINETYNINE,graph 0.91 as 1
set label 2 gprintf(" 1%% = %1.0f ns",$ONE) at $ONE, graph 0.91 right front offset -1,-1
set style arrow 2 nohead
set arrow from $ONE,0 to $ONE,graph 0.91 as 2
set label 3 gprintf("25%% = %1.0f ns",$TWENTYFIVE) at $TWENTYFIVE, graph 0.7 right front offset -1,-1
set style arrow 3 nohead
set arrow from $TWENTYFIVE,0 to $TWENTYFIVE,graph 0.7 as 3
set label 4 gprintf("75%% = %1.0f ns",$SEVENTYFIVE) at $SEVENTYFIVE, graph 0.7 left front offset 1,-1
set style arrow 4 nohead
set arrow from $SEVENTYFIVE,0 to $SEVENTYFIVE,graph 0.7 as 4
set key off
set xrange [-10000:10000]
plot \\
 "ptp-${RUN}.history" using 1:2 title "histogram" with boxes
EOF

FIFTY=`./percentile 4 50 10.1.2.128-${RUN}.log`

gnuplot <<EOF
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "128-${RUN}.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.0f ns" nomirror
set title "offset between ptp/stm32mp1"
set key top right box
set label 1 gprintf('50%% = $FIFTY ns',50) at graph 0.01,0.05 left front
plot \\
    '10.1.2.128-${RUN}.log' using 1:2 title 'tx' with line, \\
    '10.1.2.128-${RUN}.log' using 1:3 title 'rx' with line, \\
    '10.1.2.128-${RUN}.log' using 1:5 title 'offset' with line, \\
    $FIFTY title '50th percentile'
EOF

NINETYNINE=`./percentile 4 99 10.1.2.128-${RUN}.log`
SEVENTYFIVE=`./percentile 4 75 10.1.2.128-${RUN}.log`
TWENTYFIVE=`./percentile 4 25 10.1.2.128-${RUN}.log`
ONE=`./percentile 4 1 10.1.2.128-${RUN}.log`

gnuplot <<EOF
set terminal png size 900,600
set output "histogram-128-${RUN}.png"
set grid
set xtic rotate by -45 scale 0
set title "Histogram of offset between ptp/stm32mp1"
set xtics format "%1.0f ns" nomirror
set label 1 gprintf("99%% = %1.0f ns",$NINETYNINE) at $NINETYNINE, graph 0.91 left front offset 1,-1
set style arrow 1 nohead
set arrow from $NINETYNINE,0 to $NINETYNINE,graph 0.91 as 1
set label 2 gprintf(" 1%% = %1.0f ns",$ONE) at $ONE, graph 0.91 right front offset -1,-1
set style arrow 2 nohead
set arrow from $ONE,0 to $ONE,graph 0.91 as 2
set label 3 gprintf("25%% = %1.0f ns",$TWENTYFIVE) at $TWENTYFIVE, graph 0.7 right front offset -1,-1
set style arrow 3 nohead
set arrow from $TWENTYFIVE,0 to $TWENTYFIVE,graph 0.7 as 3
set label 4 gprintf("75%% = %1.0f ns",$SEVENTYFIVE) at $SEVENTYFIVE, graph 0.7 left front offset 1,-1
set style arrow 4 nohead
set arrow from $SEVENTYFIVE,0 to $SEVENTYFIVE,graph 0.7 as 4
set key off
set xrange [-20000:20000]
plot \\
 "10.1.2.128-${RUN}.history" using 1:2 title "histogram" with boxes
EOF

FIFTY=`./percentile 4 50 10.1.2.198-${RUN}.log`

gnuplot <<EOF
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "198-${RUN}.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.0f ns" nomirror
set title "offset between ptp/cheese"
set key top right box
set label 1 gprintf('50%% = $FIFTY ns',50) at graph 0.01,0.05 left front
plot \\
    '10.1.2.198-${RUN}.log' using 1:2 title 'tx' with line, \\
    '10.1.2.198-${RUN}.log' using 1:3 title 'rx' with line, \\
    '10.1.2.198-${RUN}.log' using 1:5 title 'offset' with line, \\
    $FIFTY title '50th percentile'
EOF

NINETYNINE=`./percentile 4 99 10.1.2.198-${RUN}.log`
SEVENTYFIVE=`./percentile 4 75 10.1.2.198-${RUN}.log`
TWENTYFIVE=`./percentile 4 25 10.1.2.198-${RUN}.log`
ONE=`./percentile 4 1 10.1.2.198-${RUN}.log`

gnuplot <<EOF
set terminal png size 900,600
set output "histogram-198-${RUN}.png"
set grid
set xtic rotate by -45 scale 0
set title "Histogram of offset between ptp/cheese"
set xtics format "%1.0f ns" nomirror
set label 1 gprintf("99%% = %1.0f ns",$NINETYNINE) at $NINETYNINE, graph 0.91 left front offset 1,-1
set style arrow 1 nohead
set arrow from $NINETYNINE,0 to $NINETYNINE,graph 0.91 as 1
set label 2 gprintf(" 1%% = %1.0f ns",$ONE) at $ONE, graph 0.91 right front offset -1,-1
set style arrow 2 nohead
set arrow from $ONE,0 to $ONE,graph 0.91 as 2
set label 3 gprintf("25%% = %1.0f ns",$TWENTYFIVE) at $TWENTYFIVE, graph 0.7 right front offset -1,-1
set style arrow 3 nohead
set arrow from $TWENTYFIVE,0 to $TWENTYFIVE,graph 0.7 as 3
set label 4 gprintf("75%% = %1.0f ns",$SEVENTYFIVE) at $SEVENTYFIVE, graph 0.7 left front offset 1,-1
set style arrow 4 nohead
set arrow from $SEVENTYFIVE,0 to $SEVENTYFIVE,graph 0.7 as 4
set key off
set xrange [-20000:20000]
plot \\
 "10.1.2.198-${RUN}.history" using 1:2 title "histogram" with boxes
EOF
