#!/bin/sh

#./offsets3 <run3.log >offsets3.log
#awk '($1 > 1553746248 && $1 < 1553746548) { print }' <offsets3.log >offsets3-zoom.log
#awk '($1 > 1553746248 && $1 < 1553747148) { print }' <offsets3.log >offsets3-zoom2.log
#awk '($1 > 1553746248 && $1 < 1553749848) { print }' <offsets3.log >offsets3-zoom3.log
#./jitter3 <offsets3.log >jitter3.log

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "offset3-5m.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.3f ms" nomirror
set title "offset of remote clock (5m) - 17.013ppm"
set key bottom right box
plot \\
    'offsets3-zoom.log' using 1:(\$3*1000-0.017013*(\$1-1553746248)) title 'request' with line, \
    'offsets3-zoom.log' using 1:(\$3*1000-0.017013*(\$1-1553746248)+\$2*1000) title 'response' with line
EOF

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "offset3-15m.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.3f ms" nomirror
set title "offset of remote clock (15m) - 17.296ppm"
set key bottom right box
plot \\
    'offsets3-zoom2.log' using 1:(\$3*1000-0.017296*(\$1-1553746248)) title 'request' with line, \
    'offsets3-zoom2.log' using 1:(\$3*1000-0.017296*(\$1-1553746248)+\$2*1000) title 'response' with line
EOF

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "offset3-1h.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.3f ms" nomirror
set title "offset of remote clock (1h) - 14.230ppm"
set key bottom right box
plot \\
    'offsets3-zoom3.log' using 1:(\$3*1000-0.014230*(\$1-1553746248)) title 'request' with line, \
    'offsets3-zoom3.log' using 1:(\$3*1000-0.014230*(\$1-1553746248)+\$2*1000) title 'response' with line
EOF

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "offset3.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f ms" nomirror
set title "offset of remote clock - 12.358ppm"
set key bottom right box
plot \\
    'offsets3.log' using 1:(\$3*1000-0.012358*(\$1-1553746248)) title 'request' with line, \
    'offsets3.log' using 1:(\$3*1000-0.012358*(\$1-1553746248)+\$2*1000) title 'response' with line
EOF

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "jitter3.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f us" nomirror
set title "offset change from previous second"
set key bottom right box
plot \\
    'jitter3.log' using 1:(\$3*1000000) title 'jitter' with line
EOF

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "rtt3.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f us" nomirror
set title "rtt of remote clock"
set key top left box
plot \\
    'offsets3.log' using 1:(\$2*1000000) title 'ntp server' with line
EOF

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "proc3.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.0f us" nomirror
set title "proctime of remote clock"
set key top right box
plot \\
    'offsets3.log' using 1:(\$4*1000000) title 'ntp server' with line
EOF

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "tx3.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.2f us" nomirror
set title "local software to hardware TX timestamp difference"
set key top right box
plot \\
    'offsets3.log' using 1:(\$5*1000000) title 'local' with points
EOF

