#!/bin/sh

RUN=9
TIME=2206130892

echo times
awk '{print $1-'$TIME', $2, $3, $4, $5, $6;}' <run$RUN.log >time$RUN.log
echo temps
./resist-temp <time${RUN}.log >temps${RUN}.log
echo graphs

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "inttemp${RUN}.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f F" nomirror
set title "Temperature"
set key top right box
plot \\
    'time${RUN}.log' using 1:(\$2/1000) title 'internal' with line
EOF

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "volts${RUN}.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.3f V" nomirror
set y2tics format "%1.3f V" nomirror
set title "Voltage"
set key bottom left box
plot \\
    'time${RUN}.log' using 1:(\$3/1000) title '3.3V' with points, \\
    'time${RUN}.log' using 1:(\$4/500) title '5V' with points axis x1y2
EOF

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "temp${RUN}.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f F" nomirror
set title "Temperature"
set key top right box
plot \\
    'temps${RUN}.log' using 1:(\$2-40) title 'internal-40' with line, \\
    'temps${RUN}.log' using 1:3 title 'thermistor' with line, \\
    'temps${RUN}.log' using 1:4 title 'tmp36' with line
EOF

cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "temp12-${RUN}.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f F" nomirror
set title "Temperature"
set key top right box
plot \\
    'temps${RUN}.log' using 1:(\$2-\$3) title 'internal-thermistor' with line
EOF
cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "temp13-${RUN}.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f F" nomirror
set title "Temperature"
set key top right box
plot \\
    'temps${RUN}.log' using 1:(\$2-\$4) title 'internal-tmp36' with line
EOF
cat <<EOF | gnuplot
set terminal png size 900,600
set xdata time
set timefmt "%s"
set output "temp23-${RUN}.png"
set grid
set xlabel "Time"
set format x "%d-%H:%M"
set xtic rotate by -45 scale 0
set ylabel ""
set ytics format "%1.1f F" nomirror
set title "Temperature"
set key top right box
plot \\
    'temps${RUN}.log' using 1:(\$3-\$4) title 'thermistor-tmp36' with line
EOF

