#!/usr/bin/perl

use strict;

my($first,$last);

while(<>) {
  chomp($_);
  my(@a) = split(/ /);
  if(not defined($first)) {
    $first = \@a;
  }
  $last = \@a;
}

my $ppm = -1*($last->[2]-$first->[2])/($last->[0]-$first->[0]);

printf("%d %.9f\n", $first->[0], $ppm);
